list_to_dict.py:8: error: false when calling list_to_dict(('', '')) (which returns {'': ''})
